### ISSUE TITLE
Join on properties in objects

### ISSUE THREAD

**Issue by mrdanadams** [sirensolutions/siren-join#115]
I have a document I want to join that looks like this:

```
"_source": {
  "profile": { "id" }
}
```

Where `id` is the id on the other index. Can I join with something like this?:

```
{
  "filterjoin": {
    "profile.id": {
      // indices, types, etc
      "path": "id"
    }
  }
}
```

I have this working with other fields but not with the id.

**Comment by rendel** [comment]
This should work, apart if the field is the `_id` field (See #63 for more information).

**Comment by mrdanadams** [comment]
So when joining from a profile -> story (profile has the `_id` and is referenced in story at `profile.es_id`) with this search:

```
{ "filterjoin": { "_id": { "path": "profile.es_id",
```

I get this error:

```
{
   "error": {
      "root_cause": [
         {
            "type": "parse_exception",
            "reason": "[fielddata_terms] query does not support field data type string"
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
// ...
}
```

Going the other way ("profile.es_id" -> "_id") querying stories, what would the foreign key / path be in that case?

**Comment by rendel** [comment]
Like I said in my previous comment, joining on the `_id` metafield is not possible at the moment. A fallback solution is, as suggested in #63, to add explicitly the id as a document field (not indexed but with doc values activated).
