### ISSUE TITLE
no query registered for [fielddata_terms]

### ISSUE THREAD

**Issue by codersea** [sirensolutions/siren-join#129]
when i post my query, there is something wrong like  "no query registered for [fielddata_terms]"
my query DSL as follow:

```json
{
  "query":{
       "bool":{
            "filter":{
                "filterjoin":{
                     "nl":{
                          "indices":["person_gwry"],
                          "path":"nl",
                          "query":{
                               "terms":{
                                   "typetype":"other"
                                         }
                                       }
                                   }
                              }
                         }
                     }
                 }
}
```

**Comment by scampi** [comment]
@codersea what is the curl command ?

**Comment by chrislaue** [comment]
I'm also getting this issue using 2.4.4 

My curl looks as such:

curl -X POST localhost:9200/my_index/my_index_type/_coordinate_search -d '{"query":{"filtered":{"query":{"match_all":{}},"filter":{"filterjoin":{"my_key":{"indices":["my_other_index"],"types":["my_other_type"],"path":"my_key","query":{"terms":{"state":["CA"]}}}}}}}}'

```{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "filterjoin": {
          "my_key": {
            "indices": [
              "my_other_index"
            ],
            "types": [
              "my_other_type"
            ],
            "path": "my_key",
            "query": {
              "terms": {
                "state": [
                  "CA"
                ]
              }
            }
          }
        }
      }
    }
  }
}```

**Comment by scampi** [comment]
@chrislaue maybe you don't have the plugin installed on all nodes.
Can you try running this command `curl -XGET 'http://localhost:9200/_nodes'` and check that `siren-join` appears on all data nodes ?

**Comment by chrislaue** [comment]
@scampi - This definitely seems to be the case. Thanks for the input - greatly appreciated.

**Comment by scampi** [comment]
@chrislaue no problem!
@codersea please reopen the issue if this is not the case for you.
