### ISSUE TITLE
Would you consider changing the license?

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [sirensolutions/siren-join#137]
Hi Friends!

Now that this project is unsupported, and I assume just generally abandoned, would y'all consider changing the license to something that's more permissive?  Apache 2 would be cool, BSD or even public domain would be amazing.

I have a desire to take over this code for ES 2.4 (and port to ES 5) but not with the Affero GPL attached to it.  Technically, what I want to do ingest the code into my open-source project, [ZomboDB](https://www.github.com/zombodb/zombodb/).  I don't have a desire to maintain it as a public plugin like y'all have done.

As I'm sure y'all understand, I'd rather not have to clean-room a similar feature, especially considering how well this plugin has worked over the past two years.

Thanks for your consideration!

eric

**Comment by jccq** [comment]
Hi Eric

we would be happy to support/facilitate ZomboDB users, while Siren Join is
not something we support, Vanguard (which now features fully distributed
cross cluster operations) could be quite an accelerator for Zombo. Please
write us at info@siren.io happy to explore possibilities.

Gio

[image: photo]
Giovanni Tummarello, Ph.D
CPO/Founder at Siren
A Unit 4 GTC, Mervue Park, Galway, Ireland
D +353 91 704885
<+353+91+704885?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
M +353 87 1272938
<+353+87+1272938?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
E giovanni@siren.io  <giovanni@siren.io> W http://siren.io
<http://siren.io?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren
will be atBig Data & Analytics for Pharma Summit (Philadelphia Nov 1-2,
2017)
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

**Comment by eeeebbbbrrrr** [comment]
Thanks Gio.  Should I address my email to someone else?

I'll put something together and get back to you in a day or two.

Feel free to close this issue.

**Comment by jccq** [comment]
just write to me its ok :)) ttysoon.

[image: photo]
Giovanni Tummarello, Ph.D
CPO/Founder at Siren
A Unit 4 GTC, Mervue Park, Galway, Ireland
D +353 91 704885
<+353+91+704885?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
M +353 87 1272938
<+353+87+1272938?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
E giovanni@siren.io  <giovanni@siren.io> W http://siren.io
<http://siren.io?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>

<https://twitter.com/sirensearch?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://youtube.com/c/SirenSolutionsChannel?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://vimeo.com/sirenio?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://www.twitter.com/jccq?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
Siren
will be atBig Data & Analytics for Pharma Summit (Philadelphia Nov 1-2,
2017)
<https://theinnovationenterprise.com/summits/big-data-analytics-for-pharma-summit-philadelphia-november-2017?utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature&utm_source=WiseStamp&utm_medium=email&utm_term=&utm_content=&utm_campaign=signature>
