### ISSUE TITLE
join and other filters

### ISSUE THREAD

**Issue by lesaux** [sirensolutions/siren-join#138]
Hello,

Apologies, as I'm not sure this is the right place to ask this question. Also this is in regards to Vanguard.

I am "converting" a SOLR query to Elasticsearch, so Vanguard as been useful to replicate a SOLR join i.e. 

`{!join from=field1 to=field2}field3:Value3`  into

```
{
  "query": {
      "join" : {
        "indices" : ["my-index"],
        "on" : ["field1", "field2"],
        "request" : {
          "query" : {
            "term" : {
              "field3" : "Value3"
            }
          }
        }
      }
  }
}
```

This works quite well.

However I still have other components in my solr query, such as 
`({!join from=field1 to=field2}field3:Value3)` 
AND 
`-field4:[\"\" TO *]` 
AND 
`-field5:[\"\" TO *]`.

How can I achieve this with siren/vanguard?

**Comment by rendel** [comment]
Hi @lesaux you can nest a join query clause inside a boolean clause, so you could do something like:

```
{
  "query": {
      "bool" : {
        "must" : {
          "join" : {
            "indices" : ["my-index"],
            "on" : ["field1", "field2"],
            "request" : {
              "query" : {
                "term" : {
                  "field3" : "Value3"
                }
              }
            }
          }
        },
        "must_not" : {
          "term" : {
            "field4" : "Value4"
          }
        }
      }
  }
}
```

**Comment by lesaux** [comment]
Thanks a lot. I was convinced I had tried "bool" and it wasn't working. Closing.
