### ISSUE TITLE
Upgrade to Elasticsearch 2.1.1

### ISSUE THREAD

**Issue by yehosef** [sirensolutions/siren-join#22]
Will this work with Elasticsearch 2? - if not, it would be great if it's supported.

**Comment by jccq** [comment]
Next version will have Elastic 2 compatibility :) stay tuned, and happy new
year!

**Comment by yehosef** [comment]
great to hear - I just found your site/products - looks really interesting.  Looking forward to trying out.

**Comment by rendel** [comment]
The develop branch is now compatible with Elasticsearch 2.1.1.

**Comment by yehosef** [comment]
yea!
