### ISSUE TITLE
Option to force the encoding of terms as integer instead of long

### ISSUE THREAD

**Issue by rendel** [sirensolutions/siren-join#25]

**Comment by rendel** [comment]
We can automatically detect when terms can be encoded as integer instead of long using the max value returned by the field stats.
In addition, when integer encoding can be applied, we could use a vint encoding approach to compress the set of terms, as it is more likely that these integers will not follow a random distribution (e.g., generated by hash) compared to a long value (which is likely to be a generated hash).

**Comment by rendel** [comment]
Reverting back to the original idea, it is generally better to leave the control to the user. Also, Kibi can easily detect when a field can be encoded with integers, and can recommend it to the user.

**Comment by scampi** [comment]
Should I open an issue in kibi to support this feature ? So it can give a warning.

**Comment by rendel** [comment]
Yes, I think we need an umbrella issue for the integration of the siren-join plugin with Kibi. At the moment Kibi is missing:
- an "advanced" configuration panel for the join where a user can define additional parameters such as terms encoding, order by, max term per shards, etc.
- automatic suggestion / warming when user is configuring a join: for example, kibi could warn user if he tries to configure integer encoding on a string datatype field, kibi could suggest to use the integer encoding on a numeric field with max value < integer.max_value (info we can get from a field stats query)

**Comment by scampi** [comment]
opened in https://github.com/sirensolutions/kibi-private/issues/115
