### ISSUE TITLE
Integrate a circuit breaker in the terms set computation

### ISSUE THREAD

**Issue by rendel** [sirensolutions/siren-join#29]
Currently, if the user does not set a term limit, and if the term set is too big for the available memory, this could lead to a OOME. We could add a circuit breaker to protect against this.

**Comment by jccq** [comment]
EE feature possibly?


On Fri, Feb 12, 2016 at 11:15 AM, Renaud <notifications@github.com> wrote:

> Closed #29 <https://github.com/sirensolutions/siren-join/issues/29> via
> 152655d
> <https://github.com/sirensolutions/siren-join/commit/152655dd21d70535a077f7de13c30e12ac3a3775>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/siren-join/issues/29#event-548397827>.
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions

**Comment by jccq** [comment]
EE stuff?
