### ISSUE TITLE
Upgrade to Elasticsearch 2.2

### ISSUE THREAD

**Issue by rendel** [sirensolutions/siren-join#32]

**Comment by jccq** [comment]
\o/ :)

On Mon, Feb 8, 2016 at 4:44 PM, Renaud <notifications@github.com> wrote:

> Closed #32 <https://github.com/sirensolutions/siren-join/issues/32> via
> 5d2e77d
> <https://github.com/sirensolutions/siren-join/commit/5d2e77db36005969231250b2ae2de1cf69b40be5>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sirensolutions/siren-join/issues/32#event-543068934>.
>



-- 
Giovanni Tummarello
CEO - SIREn Solutions
