### ISSUE TITLE
Elasticsearch 2.2: "No query registered for [filterjoin]"

### ISSUE THREAD

**Issue by jezell** [sirensolutions/siren-join#52]
Trying to install siren-join on Elasticsearch 2.2. Using simple dockerfile:

```
FROM elasticsearch:latest

RUN bin/plugin install solutions.siren/siren-join/2.2.0-1
```
Plugin appears in startup logs here:

`[2016-03-15 20:00:50,737][INFO ][plugins                  ] [Turac] modules [lang-expression, lang-groovy], plugins [siren-join], sites []`

However, when executing a query, filterjoin does not appear to be available:

`{"error":{"root_cause":[{"type":"query_parsing_exception","reason":"No query registered for [filterjoin]","index":"objects","line":1,"col":12}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"objects","node":"MmpX7AI2TOydZBzDwxqbUA","reason":{"type":"query_parsing_exception","reason":"No query registered for [filterjoin]","index":"objects","line":1,"col":12}}]},"status":400}`

**Comment by jezell** [comment]
Problem, was using _search endpoint in API instead of _coordinate_search.

**Comment by Gautam17** [comment]
Hello,
I'm new in elastic search..facing same issue while trying,
<pre>
POST company/_coordinate_search
{
  "query": {
    "bool": {
            "must": {
        "match_all": {}
      },
      "filter": {
        "filterjoin": {
          "mentions": {
            "indices": [
              "company"
            ],
            "path": "id",
            "query": {
              "term": {
                "name": "orient"
              }
            }
          }
        }
      }
    }
  }
}
</pre>
error=
<pre>
"root_cause": [
      {
        "type": "invalid_type_name_exception",
        "reason": "Document mapping type name can't start with '_', found: [_coordinate_search]"
      }
    ]
</pre>

can anyone help to solve this
thanks in advance

**Comment by rendel** [comment]
@Gautam17 is the plugin properly installed on all the nodes ?

**Comment by Gautam17** [comment]
@rendel  normal query like match_all is working properly.
