### ISSUE TITLE
ERROR installing plugin

### ISSUE THREAD

**Issue by amassaro** [sirensolutions/siren-join#59]
Readme docs seem to be out of date? Tried using the actual (new?) GitHub path and seems to download successfully but fails on installing the plugin ... 

**plugin install sirensolutions/siren-join**
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by scampi** [comment]
you need to follow the instructions from the readme of `master` branch https://github.com/sirensolutions/siren-join/tree/master

otherwise in the (default) `develop` branch, you have to manually create the plugin and install it from the local file.

**Comment by amassaro** [comment]
Okay so basically there is not a command line install for ES 2.3.1 yet. Thank you!

**Comment by rendel** [comment]
I have changed the default branch to "master" in order to help avoiding confusion.
