### ISSUE TITLE
available within java api

### ISSUE THREAD

**Issue by iamtiancaif** [sirensolutions/siren-join#79]
I am writing my transport client. Is there some java api to support siren-join feature?
Thanks~!

**Comment by rendel** [comment]
Yes, there is a java api available, you can have a look at the source code and unit tests for example.
Please use our user mailing list [1] to ask questions such as this one, github is for dev communication (bugs, new feature request, etc.). Thanks.

[1] https://groups.google.com/a/siren.solutions/forum/#!forum/kibi-users
