### ISSUE TITLE
Shield authentication failed to Co-ordinate search in ES 1.7.3

### ISSUE THREAD

**Issue by GaneshbabuRamamoorthy** [sirensolutions/siren-join#83]
Hi All,

We have installed siren plugin in ES 1.7.3 version and we tried using "coordinate_search" in our dev envrionment and getting the below error,
{
   "error": "ElasticsearchException[Unexpected failure while executing a terms by query action]; nested: AuthorizationException[action [indices:data/read/search/termsbyquery] is unauthorized for user [__es_system_user]]; ",
   "status": 500
}

I installed shield for our authentication purpose and we didn't create es_system_user in the shield, when we execute the query we are getting the above exception.

I have indexed sample records in local envrionment with the following link,
https://siren.solutions/relational-joins-for-elasticsearch-the-siren-join-plugin/

![coordinate search issue in siren plugin](https://cloud.githubusercontent.com/assets/20658619/17131154/c78c4bbe-5339-11e6-923e-3221c77e9d95.png)
[Filterjson Query.txt](https://github.com/sirensolutions/siren-join/files/383386/Filterjson.Query.txt)

Please guide us to resolve this issue.

Thanks,
Ganeshbabu R

**Comment by rendel** [comment]
Hi,

Shield compatibility was added to version 2.2.0 (see issue #45). Unfortunately, we are not planning to backport this feature to 1.7.3.
