### ISSUE TITLE
Add not exists functionality

### ISSUE THREAD

**Issue by rostiar** [sirensolutions/siren-join#88]
Hi,

It would be nice to add NOT EXISTS functionality

Thanks, Rostislav.

**Comment by scampi** [comment]
Can you describe what you would like ?

**Comment by rostiar** [comment]
Hi @scampi,
For example I have collection of documents from my app servers. It looks like client x were served by server A, client x were served by server B and so on... Now I need to know what clients were server by server A but were not served by server B during the same period of time. In SQL it would be not exists query. Now siren-join supports only exists and I cannot run not exists query.
Rostislav.

**Comment by scampi** [comment]
The siren-join query is just like any other query in ES. Therefore, you can use the [bool query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) to wrap the siren-join in a `must_not` clause.

**Comment by rostiar** [comment]
Good idea, thanks. I will try it and get back.
